### ISSUE TITLE
This example doesn't reflect explicitly the difference between shared and dedicated workers

### ISSUE THREAD

**Issue by zetmann** [mdn/simple-shared-worker#7]
It works, however it can be easily rewritten with dedicated worker and will work exactly the same.
Would be cool to have an example that will show why would we use shared workers and not other one.

**Comment by mbartlett21** [comment]
Maybe we can change each page to have a single input and basically have the worker just have a counter and just add infinitely.

**Comment by schalkneethling** [comment]
Hey @zetmann and @mbartlett21! Thank you for opening this issue. I believe that the [simple-web-worker](https://github.com/mdn/dom-examples/tree/master/web-workers/simple-web-worker) example is what you might have wanted?  We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant and not answered by the referenced example. Thank you.
